[project]
name = "borunte"
version = "0.1.0"
description = "Borunte robot control test"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "loguru>=0.7.3",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "opencv-contrib-python>=4.11.0.86",
    "pandas>=2.3.2",
    "plotly>=6.3.1",
    "pymodbus",
    "pynput>=1.8.1",
    "pyrealsense2>=2.56.5.9235",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
